services:

  web:
    build:
      context: ./app
    container_name: student_web
    restart: unless-stopped

    volumes:
      - ./app:/app

    expose:
      - "8000"

    environment:
      DB_NAME: student_db
      DB_USER: student_user
      DB_PASSWORD: Student@2026Strong
      DB_HOST: mysql
      DB_PORT: 3306

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - frontend
      - backend


  mysql:
    image: mysql:8.0
    container_name: student_mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: student_db
      MYSQL_USER: student_user
      MYSQL_PASSWORD: Student@2026Strong
      MYSQL_ROOT_PASSWORD: Root@2026Strong

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: student_phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8081:80"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - frontend
      - backend


  nginx:
    image: nginx:alpine
    container_name: student_nginx
    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - web

    networks:
      - frontend


networks:
  frontend:
  backend:
    internal: true


volumes:
  mysql_data: