# Generated by Django 5.2.6 on 2026-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('class_name', models.CharField(max_length=100, verbose_name='Lớp học')),
                ('major', models.CharField(max_length=100, verbose_name='Khoa/Ngành')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email học tập')),
                ('phone', models.CharField(max_length=10, verbose_name='Số điện thoại')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm trung bình hệ 10')),
            ],
        ),
    ]
