# Generated by Django 5.2.6 on 2026-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('class_name', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('major', models.CharField(max_length=100, verbose_name='Khoa')),
            ],
        ),
    ]
