# Generated by Django 5.2.6 on 2026-09-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Môn học')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Điểm')),
                ('semester', models.CharField(max_length=50, verbose_name='Học kỳ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Sinh viên')),
            ],
        ),
    ]
