# Generated by Django 5.2.6 on 2026-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='score',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='Năm học'),
        ),
        migrations.AddField(
            model_name='grade',
            name='classification',
            field=models.CharField(choices=[('Xuất sắc', 'Xuất sắc'), ('Giỏi', 'Giỏi'), ('Khá', 'Khá'), ('Trung bình', 'Trung bình'), ('Yếu', 'Yếu')], default='Khá', max_length=20, verbose_name='Xếp loại'),
        ),
        migrations.AddField(
            model_name='grade',
            name='score_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Điểm hệ 10'),
        ),
        migrations.AddField(
            model_name='grade',
            name='score_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Điểm hệ 4'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.CharField(max_length=20, verbose_name='Học kỳ'),
        ),
    ]
